name: Create Release with STL Files

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow on tags starting with 'v' (e.g., v1.0, v2.1.3)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install OpenSCAD
      run: |
        sudo apt-get update
        sudo apt-get install -y openscad
    - name: Render OpenSCAD files to STL
      run: |
        mkdir stl
        python generate_stls.py

    - name: Create release and upload assets
      uses: ncipollo/release-action@v1
      with:
        artifacts: stl/*.stl
