name: Render files to STL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install OpenSCAD
      run: |
        sudo apt-get update
        sudo apt-get install -y openscad
    - name: Render OpenSCAD files to STL
      run: |
        mkdir stl
        ls
        python generate_stls.py
    - name: Upload STL files
      uses: actions/upload-artifact@v4
      with:
        name: stl-files
        path: stl/
